name: CI
on:
  push: {}

jobs:

  config:
    name: Get Config
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.getconfig.outputs.config }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full clone to also get the tags to get the right salt version
      - name: Get Config
        id: getconfig
        run: python3 genconfig.py
