name: CI
on:
  push: {}
  workflow_dispatch: {}


jobs:

  testlinux:

    runs-on: ubuntu-22.04
    environment: ci
    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Random Failure
        shell: bash
        run: |
          cat <<"EOF" > cmd.py
          import sys
          import random

          random.seed()
          if random.randint(0, 1):
              sys.exit(0)
          else:
              sys.exit(1)
          EOF
          python3 cmd.py



