name: Release
run-name: "Release (branch: ${{ github.ref_name }}; version: ${{ inputs.version }})"

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

permissions:
  contents: write  # To be able to publish the release
  pull-requests: write

jobs:

  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup GnuPG
        run: |
          sudo install -d -m 0700 -o "$(id -u)" -g "$(id -g)" /run/gpg
          GNUPGHOME="$(mktemp -d -p /run/gpg)"
          echo "GNUPGHOME=${GNUPGHOME}" >> "$GITHUB_ENV"
          cat <<EOF > "${GNUPGHOME}/gpg.conf"
          batch
          no-tty
          pinentry-mode loopback
          EOF
          echo "${SIGNING_GPG_PASSPHRASE}" > "${GNUPGHOME}/passphrase" 
          echo "passphrase-file ${GNUPGHOME}/passphrase" >> "${GNUPGHOME}/gpg.conf"
          echo "${SIGNING_GPG_KEY}" | gpg --import -
          sync


      - run: |
          git config --global --add safe.directory "$(pwd)"
          git config --global user.name "Salt Project Packaging"
          git config --global user.email saltproject-packaging@vmware.com

      - run: |
          echo 123 > meh
          git add meh
          git commit -m meh
          git tag -m "Release ${{ inputs.version }}" -a v${{ inputs.version }}

      - name: Push Changes
        uses: ad-m/github-push-action@b87afee92c6e70ea888be6203a3e9426fda49839
        with:
          ssh: true
          tags: true
          atomic: true
          branch: ${{ github.ref }}

      - name: Get release
        id: get_release
        uses: agners/get-draft-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.get_release.outputs.id }}
