name: Schedule
on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: '*/5 * * * *'

permissions:
  contents: read  # for dorny/paths-filter to fetch a list of changed files
  pull-requests: read  # for dorny/paths-filter to read pull requests
  actions: write  # to trigger branch nightly builds

jobs:
  trigger-branch-nightly-builds:
    name: Trigger Branch Workflows
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        branch: [main, foo]
    steps:
      - name: Trigger ${{ matrix.branch }} branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run ci.yml --repo ${{ github.repository }} --ref ${{ matrix.branch }}
