---
name: Draft Github Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version

permissions:
  contents: write

jobs:

  create-github-release:
    name: Draft Release v${{ inputs.salt-version }}
    runs-on: ubuntu-22.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - run: |
          git config --global --add safe.directory "$(pwd)"
          git config --global user.name "Salt Project Packaging"
          git config --global user.email saltproject-packaging@vmware.com

      - name: Change code
        run: |
          openssl rand -hex 12 > meh
          git add meh
          git commit -m "Release v${{ inputs.version }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: "Release v${{ inputs.version }}"
          tag_name: v${{ inputs.version }}
          draft: true
          prerelease: false

      - name: Release Output
        run: echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> "$GITHUB_OUTPUT"
