---
name: Test

on:
  workflow_call:
    inputs:
      config:
        type: string
        required: true
        description: Configuration

jobs:
  testit:
    runs-on: ubuntu-latest
    needs:
     - config
    steps:
      - name: Test it a
        run: echo ${{ fromJSON(inputs.config)['foo'] }}

      - name: Test it 3
        run: echo ${{ fromJson(inputs.config)['moo'] }}
